using System.Collections.Generic;
using UnityEngine;

public class WordBank : MonoBehaviour
{
    private  List<string> myWordbank = new List<string>() {"aalii", "added", "adder", "addle", "adios", "adits",
    "adore", "adorn", "aedes", "aeons", "aerie", "aided", "aider", "aides", "ailed", "aioli", "aired", "airer",
    "airns", "airts", "aisle", "aland", "alane", "alans", "alants", "alate", "alder", "aldol", "alert", "alias",
    "alien", "aline", "alist", "allee", "allod", "allot", "aloes", "aloin", "alone", "altar", "alter", "altos",
    "andro", "anear", "anele", "anent", "anile", "anils", "anion", "anise", "anlas", "annal", "annas", "anoas", 
    "anode", "anole", "ansae", "antae", "antas", "anted", "antes", "antis", "antra", "antre", "aorta", "ardor",
    "areae", "areas", "arena", "arene", "arete", "arias", "ariel", "arils", "arise", "arles", "aroid", "arose",
    "arras", "arris", "arses", "arsis", "arson", "artal", "artel", "asana", "aside", "assai", "asses", "asset",
    "aster", "astir", "atilt", "atlas", "atoll", "atone", "atria", "attar", "atted", "dadas", "dados", "dales", 
    "danio", "dared", "darer", "dares", "darns", "darts", "dated", "dater", "dates", "datos", "datto", "deads",
    "deair", "deals", "dealt", "deans", "dears", "dedal", "deeds", "deers", "deets", "deils", "deist", "deled",
    "deles", "delis", "dells", "delta", "delts", "denar", "denes", "dense", "dents", "derat", "desis", "deter",
    "dials", "didie", "didos", "didst", "diene", "diets", "dildo", "dills", "dinar", "dined", "diner", "dines",
    "dinos", "dints", "diode", "diols", "direr", "dirls", "dirts", "ditas", "dites", "ditto", "doats", "dodos",
    "doers", "doest", "doits", "doled", "doles", "dolls", "dolor", "dolts", "donas", "donee", "donna", "donne", 
    "donor", "doors", "dores", "dorrs", "dorsa", "dosai", "dosas", "dosed", "doser", "doses", "dotal", "doted", 
    "doter", "dotes", "drail", "drain", "drats", "dread", "drear", "dreed", "drees", "dress", "drest", "dried", 
    "drier", "dries", "drill", "droid", "droit", "droll", "drone", "drool", "dross", "eared", "earls", "earns",
    "eased", "easel", "easer", "eases", "easts", "eaten", "eater", "edits", "eeled", "eerie", "eider", "eidos",
    "elain", "eland", "elans", "elate", "elder", "elide", "elint", "elite", "eloin", "enate", "ended", "ender",
    "enols", "enrol", "enter", "entia", "eosin", "erase", "ernes", "erode", "erose", "erred", "error", "erses",
    "esnes", "esses", "ester", "etnas", "ideal", "ideas", "ident", "idiot", "idled", "idler", "idles", "idols",
    "ileal", "iliad", "ilial", "iller", "inane", "indie", "indol", "indri", "inert", "inion", "inlet", "inned",
    "inner", "innie", "inset", "inter", "intis", "intro", "iodid", "iodin", "iotas", "irade", "irate", "irids",
    "irone", "irons", "isled", "isles", "islet", "issei", "istle", "laari", "laded", "laden", "lader", "lades",
    "laird", "lairs", "lalls", "lanai", "lands", "lanes", "lards", "laree", "lares", "laris", "larns", "larnt",
    "lased", "laser", "lases", "lassi", "lasso", "lasts", "lated", "laten", "later", "latte", "leads", "leans",
    "leant", "learn", "lears", "lease", "least", "ledes", "leers", "leets", "lends", "lenes", "lenis", "lenos",
    "lense", "lento", "leone", "liana", "liane", "liard", "liars", "lidar", "lidos", "liens", "liers", "lilos",
    "lilse", "lilts", "lined", "linen", "liner", "lines", "linin", "linns", "linos", "lints", "lions", "liras",
    "lirot", "lists", "litai", "litas", "liter", "lites", "litre", "llano", "loads", "loans", "loden", "lodes", 
    "loess", "loids", "loins", "lolls", "loner", "looed", "looie", "loons", "loose", "loots", "loral", "loran",
    "lords", "lores", "loris", "losel", "loser", "loses", "lotas", "lotos", "lotsa", "lotta", "lotte", "lotto",
    "naans", "nadas", "nadir", "naiad", "nails", "naira", "nalas", "naled", "nanas", "nanna", "nanos", "nards",
    "nares", "naris", "nasal", "natal", "nates", "natto", "nears", "neats", "needs", "neist", "nenes", "neons",
    "nerds", "nerol", "nerts", "nests", "netts", "nidal", "nided", "nides", "nills", "niner", "nines", "ninon", 
    "nisei", "niter", "nites", "nitid", "niton", "nitre", "nitro", "nodal", "nodes", "noels", "noils", "noirs", 
    "noise", "nolos", "nonas", "nones", "nonet", "nonis", "noons", "noose", "noria", "noris", "nosed", "noses",
    "notal", "noted", "noter", "notes", "oared", "oases", "oasis", "oasts", "oaten", "oater", "odder", "odeon", 
    "odist", "odors", "oidia", "oiled", "oiler", "olden", "older", "oldie", "olein", "oleos", "olios", "ollas", 
    "ollie", "onion", "onset", "oorie", "ootid", "orals", "orate", "order", "ordos", "oread", "oriel", "orles",
    "orlon", "ornis", "orris", "osier", "ossia", "ostia", "ottar", "otter", "ottos", "radar", "radii", "radio",
    "radon", "raias", "raids", "rails", "rains", "raise", "raita", "rales", "rando", "rands", "ranee", "ranid", 
    "ranis", "rants", "rared", "rarer", "rares", "rased", "raser", "rases", "ratal", "ratan", "rated", "ratel",
    "rater", "rates", "ratio", "ratos", "readd", "reads", "reais", "reals", "rears", "reata", "redan", "redds", 
    "reded", "redes", "redia", "redid", "redon", "redos", "reeds", "reels", "reest", "reins", "relet", "relit",
    "renal", "rends", "renin", "renos", "rente", "rents", "reoil", "reran", "resat", "resee", "reses", "reset",
    "resid", "resin", "resit", "resod", "rests", "retia", "retie", "retro", "rials", "riant", "riata", "rider", 
    "rides", "riels", "riled", "riles", "rille", "rills", "rinds", "rinse", "riots", "risen", "riser", "rises",
    "rites", "roads", "roans", "roars", "roast", "rodeo", "rodes", "roils", "roles", "rolls", "ronde", "rondo",
    "ronin", "roods", "roose", "roost", "roots", "rosed", "roses", "roset", "rosin", "rosti", "rotas", "rotes", 
    "rotis", "rotls", "rotor", "rotors", "rotte", "sades", "sadis", "saids", "sails", "sains", "saint", "salad",
    "salon", "sands", "saned", "saner", "santo", "sards", "sarin", "sarod", "sated", "sates", "satin", "satis", 
    "seals", "sears", "seats", "sedan", "seder", "seeds", "seels", "seers", "seine", "seise", "selle", "sells",
    "sends", "senes", "senna", "senor", "sensa", "sense", "sente", "senti", "sents", "serai", "seral", "sered", 
    "serer", "seres", "serin", "setae", "setal", "seton", "setts", "sials", "sided", "sides", "sidle", "silds", 
    "sills", "silos", "silts", "sines", "sired", "siree", "siren", "sires", "sirra", "sisal", "sises", "sitar",
    "sited", "sites", "slain", "slant", "slate", "slats", "sleds", "sleet", "slide", "slier", "slits", "sloes", 
    "sloid", "slots", "snail", "snare", "snarl", "sneds", "sneer", "snell", "snide", "snits", "snood", "snool",
    "snoot", "snore", "snort", "snots", "soars", "sodas", "soils", "solan", "solar", "solas", "soldi", "soldo",
    "soled", "solei", "soles", "solid", "solon", "solos", "sonar", "sonde", "sones", "soots", "soras", "sords", 
    "sored", "sorel", "sorer", "sores", "sorns", "sorta", "sorts", "sotol", "stade", "staid", "stain", "stair",
    "stale", "stall", "stand", "stane", "stans", "stare", "stars", "start", "state", "stats", "stead", "steal", 
    "steed", "steel", "steer", "stein", "stela", "stele", "steno", "stent", "stere", "stern", "stets", "stied",
    "stile", "still", "stilt", "stint", "stirs", "stoae", "stoai", "stoas", "stoat", "stole", "stone", "stood",
    "stool", "store", "stoss", "stots", "stott", "stria", "taels", "tails", "tains", "taint", "talar", "talas", 
    "taler", "tales", "talls", "talon", "tanto", "tardo", "tared", "tares", "tarns", "taros", "tarot", "tarre", 
    "tarsi", "tarts", "tased", "taser", "tases", "tasse", "tasso", "taste", "tatar", "tater", "tates", "teals",
    "tears", "tease", "teats", "teels", "teens", "teiid", "teind", "teins", "teles", "telia", "tells", "teloi", 
    "telos", "tends", "tenet", "tenia", "tenne", "tenno", "tenon", "tenor", "tense", "tents", "terai", "teres",
    "terne", "terns", "terra", "terse", "tesla", "testa", "tests", "tetra", "tetri", "tians", "tiara", "tidal", 
    "tided", "tides", "tiers", "tilde", "tiled", "tiler", "tiles", "tills", "tilts", "tinea", "tined", "tines", 
    "tints", "tired", "tires", "tirls", "tiros", "titan", "titer", "title", "titre", "toads", "toast", "toeas", 
    "toile", "toils", "toits", "tolan", "tolar", "tolas", "toled", "toles", "tolls", "tolts", "tonal", "tondi", 
    "tondo", "toned", "toner", "tones", "tonne", "tools", "toons", "toots", "toras", "tores", "torii", "toros", 
    "torot", "torrs", "torse", "torsi", "torso", "torta", "torte", "torts", "tosas", "total", "toted", "toter", 
    "totes", "trade", "trads", "trail", "train", "trait", "trans", "trass", "tread", "treat", "treed", "treen", 
    "trees", "trend", "tress", "trets", "triad", "trial", "tried", "trier", "tries", "trill", "trine", "triol", 
    "trios", "trite", "trode", "trois", "troll", "trona", "trone", "trots", "tsade", "tsadi", "tsars"};


    void Start()
    {
        
    }
}
